#!/usrlocal/bin/gawk -f

BEGIN {
  srand();
  for (i = 0; i < 50; i++) {
    a = int(rand() * 3);
    do {b = int(rand() * 3)} while (b == a);
    do {c = int(rand() * 3)} while (c == a || c == b);
    b = (a + 1) % 3;
    c = (b + 1) % 3;
    print "name: {" a " " b " " c " " a " " b " " c "} 6";
    print "i:" a " t:" b;
    print "i:" b " t:" c;
    print "i:" c " t:" a;
    print "i:" a " t:" b;
    print "i:" b " t:" c;
    print "i:" c " t:4;";
  }
  exit;
}
